import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideFileText } from '@lucide/angular';

@Component({
  selector: 'app-terms-page',
  imports: [RouterLink, LucideFileText],
  template: `
    <div class="mari-public-container py-10 sm:py-14">
      <article class="mx-auto max-w-2xl">
        <span
          class="mari-chip bg-mari-primary-light text-mari-primary-dark ring-1 ring-mari-primary-muted/40"
        >
          <svg lucideFileText [size]="12"></svg>
          Legal
        </span>
        <h1 class="mt-4 text-2xl font-bold text-mari-text sm:text-3xl">Terms of Service</h1>
        <p class="mt-2 text-sm text-mari-text-tertiary">Last updated: June 18, 2026</p>

        <div class="mari-surface-elevated mt-8 space-y-6 p-6 text-sm leading-relaxed text-mari-text-secondary sm:p-8">
          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Agreement</h2>
            <p>
              By creating an account or using Mari, you agree to these Terms. If you do not agree, do
              not use the service. This is placeholder copy — replace with counsel-reviewed text before
              a public launch.
            </p>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">The service</h2>
            <p>
              Mari provides a personal student workspace: task management, course organization,
              scheduling, Pomodoro timer, and AI-assisted study sets from PDF uploads. Features may
              change; we may add, modify, or discontinue functionality with reasonable notice when
              possible.
            </p>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Your account</h2>
            <ul class="list-inside list-disc space-y-2">
              <li>You must provide accurate information and keep your credentials secure.</li>
              <li>You are responsible for activity under your account.</li>
              <li>You must be old enough to consent to these Terms in your jurisdiction (typically 13+ with parental consent, or 18+).</li>
            </ul>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Acceptable use</h2>
            <p>You agree not to:</p>
            <ul class="mt-2 list-inside list-disc space-y-2">
              <li>Upload unlawful, infringing, or harmful content.</li>
              <li>Attempt to bypass security, quotas, or access other users’ data.</li>
              <li>Abuse AI features (spam, automated scraping, or reselling generated content as a service).</li>
              <li>Reverse engineer or disrupt the app or its infrastructure.</li>
            </ul>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">AI-generated content</h2>
            <p>
              Study sets produced from PDFs are generated by AI and may contain errors. They are for
              study aid only — verify important facts against your course materials. We do not guarantee
              accuracy or exam outcomes.
            </p>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Plans & billing</h2>
            <p>
              Mari offers a free tier with limited AI PDF imports per month. Paid Pro plans (when
              available) will be billed through Stripe subject to separate pricing shown in the app.
              Refunds and cancellation terms will be stated at checkout.
            </p>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Disclaimer</h2>
            <p>
              Mari is provided “as is” without warranties of any kind. To the fullest extent permitted
              by law, we are not liable for indirect, incidental, or consequential damages arising from
              your use of the app.
            </p>
          </section>

          <section>
            <h2 class="mb-2 text-base font-semibold text-mari-text">Contact</h2>
            <p>
              Questions about these Terms? Email
              <a href="mailto:support@mari.app" class="font-medium text-mari-primary hover:underline"
                >support@mari.app</a
              >
              (placeholder address).
            </p>
          </section>
        </div>

        <p class="mt-8 text-center text-sm text-mari-text-secondary">
          See also
          <a routerLink="/privacy" class="font-semibold text-mari-primary hover:underline">Privacy Policy</a>
          ·
          <a routerLink="/" class="font-semibold text-mari-primary hover:underline">Back to home</a>
        </p>
      </article>
    </div>
  `,
})
export class TermsPage {}
